version: '2'
services:
  elasticsearch:
    image: elasticsearch:6.8.13
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - docker-magento-mcx
