version: '2'
services:
  apache:
    image: rafaelcgstz/magento2
    # restart: unless-stopped
    # build: .
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80" # web
      # - "35729:35729" # live reload
    volumes:
      - ./src:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - docker-magento-mcx

  db:
    image: mariadb
    # restart: unless-stopped
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - docker-magento-mcx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # restart: unless-stopped
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_USER=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - docker-magento-mcx

  redis:
    image: redis
    # restart: unless-stopped
    ports:
     - 6379
    networks:
      - docker-magento-mcx

  redis-session:
    image: redis
    # restart: unless-stopped
    ports:
     - 6379
    networks:
      - docker-magento-mcx

  mailhog:
    image: mailhog/mailhog
    # restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - docker-magento-mcx

networks:
  docker-magento-mcx:
    driver: bridge

volumes:
  dbdata:
    driver: local